# Generated by Django 4.2.30 on 2026-04-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='default_block_message',
            field=models.CharField(blank=True, default='Du wurdest für diese Wishlist gesperrt.', max_length=300, verbose_name='Standard Sperrnachricht (öffentlich)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='default_block_reason',
            field=models.CharField(blank=True, default='Unangemessene Eingaben', max_length=300, verbose_name='Standard Sperrgrund (intern)'),
        ),
        migrations.AddField(
            model_name='blockedclient',
            name='public_message',
            field=models.CharField(blank=True, help_text='Wird dem gesperrten User angezeigt', max_length=300, verbose_name='Sperrnachricht (öffentlich)'),
        ),
        migrations.AddField(
            model_name='event',
            name='default_block_message',
            field=models.CharField(blank=True, default='Du wurdest für diese Wishlist gesperrt.', max_length=300, verbose_name='Standard Sperrnachricht (öffentlich)'),
        ),
        migrations.AddField(
            model_name='event',
            name='default_block_reason',
            field=models.CharField(blank=True, default='Unangemessene Eingaben', max_length=300, verbose_name='Standard Sperrgrund (intern)'),
        ),
        migrations.AlterField(
            model_name='blockedclient',
            name='reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='Grund (intern)'),
        ),
    ]
