# Generated by Django 4.2.30 on 2026-04-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_appconfig_default_block_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.AddField(
            model_name='appconfig',
            name='dj_address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='dj_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='dj_real_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Echter Name'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='dj_website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='no_event_message',
            field=models.CharField(blank=True, default='Aktuell ist kein Event aktiv. Buche jetzt deinen DJ!', max_length=300, verbose_name='Kein-Event-Nachricht (öffentlich)'),
        ),
        migrations.AddField(
            model_name='event',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='event',
            name='address_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Straße + Nr.'),
        ),
        migrations.AddField(
            model_name='event',
            name='address_zip',
            field=models.CharField(blank=True, max_length=10, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='event',
            name='spotify_preselection_playlist_id',
            field=models.CharField(blank=True, help_text='Automatisch erstellt bei Event-Erstellung', max_length=100, verbose_name='Spotify Vorauswahl Playlist'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='dj_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='dj_name',
            field=models.CharField(default='DJ', max_length=100, verbose_name='DJ Name / Künstlername'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Veranstaltungsort'),
        ),
        migrations.AlterField(
            model_name='event',
            name='spotify_playlist_id',
            field=models.CharField(blank=True, help_text='ID oder URL — wird automatisch gekürzt', max_length=100, verbose_name='Spotify Wishlist Playlist'),
        ),
    ]
