# Generated by Django 4.2.30 on 2026-04-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_remove_event_address_appconfig_dj_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='spotify_remove_on_played',
            field=models.BooleanField(default=True, verbose_name='Gespielt → aus Spotify entfernen'),
        ),
    ]
