# Generated by Django 4.2.30 on 2026-05-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_event_spotify_remove_on_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='songwish',
            name='audio_acousticness',
            field=models.FloatField(blank=True, null=True, verbose_name='Akustik'),
        ),
        migrations.AddField(
            model_name='songwish',
            name='audio_bpm',
            field=models.FloatField(blank=True, null=True, verbose_name='BPM'),
        ),
        migrations.AddField(
            model_name='songwish',
            name='audio_danceability',
            field=models.FloatField(blank=True, null=True, verbose_name='Tanzbarkeit'),
        ),
        migrations.AddField(
            model_name='songwish',
            name='audio_energy',
            field=models.FloatField(blank=True, null=True, verbose_name='Energie'),
        ),
        migrations.AddField(
            model_name='songwish',
            name='audio_instrumentalness',
            field=models.FloatField(blank=True, null=True, verbose_name='Instrumental'),
        ),
        migrations.AddField(
            model_name='songwish',
            name='audio_valence',
            field=models.FloatField(blank=True, null=True, verbose_name='Stimmung'),
        ),
    ]
