# Generated by Django 4.2.30 on 2026-05-18 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_songwish_audio_acousticness_songwish_audio_bpm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_count', models.PositiveIntegerField(default=0, verbose_name='Gästeanzahl')),
                ('threshold', models.PositiveIntegerField(default=50, verbose_name='Schwellenwert Gäste')),
                ('rate_1', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preis/Person bis Schwelle (€)')),
                ('rate_2', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preis/Person über Schwelle (€)')),
                ('base_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Grundgebühr (€)')),
                ('tech_package', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Technik-Pauschale (€)')),
                ('tech_required', models.BooleanField(default=False, verbose_name='Technik benötigt')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Endreinigung (€)')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='wishlist.event')),
            ],
            options={
                'verbose_name': 'Event-Angebot',
                'verbose_name_plural': 'Event-Angebote',
            },
        ),
    ]
