# Generated by Django 4.2.30 on 2026-05-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_add_eventoffer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('expression', models.CharField(max_length=500, verbose_name='Formel')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Preis-Formel',
                'verbose_name_plural': 'Preis-Formeln',
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Beschreibung')),
                ('condition_json', models.JSONField(default=list, verbose_name='Bedingungen')),
                ('effect_type', models.CharField(choices=[('percent_add', 'Prozent-Aufschlag'), ('flat_add', 'Pauschale hinzu'), ('flat_set', 'Pauschale setzen')], max_length=20, verbose_name='Effekt-Typ')),
                ('effect_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Effekt-Wert')),
                ('applies_to', models.CharField(choices=[('subtotal', 'Zwischensumme'), ('base', 'Grundpreis'), ('tech', 'Technik')], default='subtotal', max_length=20, verbose_name='Bezieht sich auf')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
            ],
            options={
                'verbose_name': 'Preis-Regel',
                'verbose_name_plural': 'Preis-Regeln',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PricingWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('workflow_json', models.JSONField(default=list, verbose_name='Workflow-Blöcke')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standard')),
            ],
            options={
                'verbose_name': 'Preis-Workflow',
                'verbose_name_plural': 'Preis-Workflows',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Entfernung (km)'),
        ),
        migrations.AddField(
            model_name='eventpricecalculation',
            name='calculation_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Berechnungs-Snapshot'),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Öffentlich sichtbar'),
        ),
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Grundpreis (€)')),
                ('badge_label', models.CharField(blank=True, max_length=50, verbose_name='Badge')),
                ('badge_color', models.CharField(blank=True, max_length=20, verbose_name='Badge-Farbe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_public', models.BooleanField(default=True, verbose_name='Öffentlich sichtbar')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('included_items', models.ManyToManyField(blank=True, to='wishlist.priceitem', verbose_name='Enthaltene Posten')),
            ],
            options={
                'verbose_name': 'Preis-Paket',
                'verbose_name_plural': 'Preis-Pakete',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='eventpricecalculation',
            name='applied_rules',
            field=models.ManyToManyField(blank=True, to='wishlist.pricingrule', verbose_name='Angewandte Regeln'),
        ),
        migrations.AddField(
            model_name='eventpricecalculation',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wishlist.pricingformula', verbose_name='Formel'),
        ),
        migrations.AddField(
            model_name='eventpricecalculation',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wishlist.pricingpackage', verbose_name='Paket'),
        ),
    ]
