# Generated by Django 4.2.30 on 2026-05-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_pricing_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpricecalculation',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wishlist.pricingworkflow', verbose_name='Workflow'),
        ),
    ]
