# Generated by Django 4.2.30 on 2026-06-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_add_workflow_to_calc'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='dj_home_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Für die Anfahrts-Berechnung im Buchungsformular', max_digits=9, null=True, verbose_name='Standort Breitengrad'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='dj_home_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Standort Längengrad'),
        ),
    ]
