# Generated by Django 5.1 on 2026-08-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0009_appconfig_dj_home_lat_appconfig_dj_home_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='google_review_url',
            field=models.URLField(blank=True, help_text='Aus dem Google-Business-Profil: Rezensionen → Mehr Rezensionen erhalten', verbose_name='Google-Bewertungslink'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='review_request_delay_days',
            field=models.PositiveIntegerField(default=2, verbose_name='Wartezeit nach Event (Tage)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='review_request_email_body',
            field=models.TextField(blank=True, default='Hallo {client_name},\n\nvielen Dank, dass ich bei "{event_name}" am {event_date} in {location} für die Musik sorgen durfte!\n\nWenn dir der Abend gefallen hat, freue ich mich sehr über eine kurze Bewertung bei Google — das dauert keine Minute und hilft mir enorm weiter:\n{review_url}\n\nBeste Grüße,\n{dj_name}', help_text='Platzhalter: {client_name}, {event_name}, {event_date}, {location}, {dj_name}, {review_url}', verbose_name='Bewertungs-Mail Text'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='review_request_email_subject',
            field=models.CharField(default='Wie war euer Abend? 🎶', max_length=200, verbose_name='Bewertungs-Mail Betreff'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='review_request_enabled',
            field=models.BooleanField(default=False, help_text='Sendet nach jedem Event eine Nachfass-Mail. Erfordert einen Bewertungslink.', verbose_name='Automatische Bewertungsanfragen'),
        ),
        migrations.AddField(
            model_name='event',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt der automatischen Nachfass-Mail. Leer = noch nicht gesendet.', null=True, verbose_name='Bewertungsanfrage gesendet'),
        ),
    ]
